name: Update Database Daily

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  update-database:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: flights
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install psycopg2 faker

      - name: Run Update Script
        env:
          DB_NAME: flights
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_HOST: localhost
          DB_PORT: 5432
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          python update_database.py

      - name: Dump PostgreSQL Database
        env:
          PGPASSWORD: postgres
        run: |
          pg_dump -h localhost -U postgres -d flights > flights_backup.sql

      - name: Commit and Push Backup
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          mv flights_backup.sql backups/flights_backup.sql
          git add backups/flights_backup.sql
          git commit -m "Update database backup"
          git push
