name: Update Database Daily

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  update-database:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1234
          POSTGRES_DB: flights
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install psycopg2 faker

      - name: Check Database Connection
        env:
          PGPASSWORD: postgres
        run: |
          pg_isready -h localhost -p 5432 -U postgres || exit 1

      - name: Run Update Script
        env:
          DB_NAME: flights
          DB_USER: postgres
          DB_PASSWORD: 1234
          DB_HOST: localhost
          DB_PORT: 5432
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          python update_database.py

      - name: Dump PostgreSQL Database
        env:
          PGPASSWORD: postgres
        run: |
          pg_dump -h localhost -U postgres -d flights > flights_backup.sql

      - name: Upload Database Backup
        uses: actions/upload-artifact@v3
        with:
          name: flights-backup
          path: flights_backup.sql
